### ISSUE TITLE
Can existing content be viewed only through markdown?

### ISSUE THREAD

**Issue by Wukong-SCUT** [Evolutionary-Intelligence/EC-A-Modern-Perspective#2]
I want to better read the existing content, but it seems that I can only download markdown? And it’s divided into chapters? Is there a complete markdown download or other formats? Would like a more complete read. Thank you for your work and writing!

**Comment by Evolutionary-Intelligence** [comment]
@Wukong-SCUT Thanks for your interest on this ongoing book. We are still writing this open book. Because currently we are busy in other things, we will actively update it in the near future. **Apologize this delay**. Since we adopt an open way to write this, we welcome anyone to contribute this project.

**Comment by Wukong-SCUT** [comment]
Your recent work is quite excellent. The development of pop and DCC is detailed and professional. In addition, the convergence research on cc is also a good focus. I look forward to your future work!

**Comment by Evolutionary-Intelligence** [comment]
Thanks very much again for your interests on our previous works. I also thanks the (essential) mathematical helps from Chang Shao whose academic background is mathematics to make the (interesting) convergence proof of CC possible.
